# Generated by Django 4.0.4 on 2024-03-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomyshow',
            name='show_themes',
            field=models.ManyToManyField(to='planetarium.showtheme'),
        ),
    ]
